package br.com.minhasortemegasena.model

data class LotteryModel(
    val acumulado: Boolean?,
    val dataApuracao: String = "",
    val dataProximoConcurso: String = "",
    val dezenasSorteadasOrdemSorteio: List<String>?,
    val exibirDetalhamentoPorCidade: Boolean?,
    val id: Any?,
    val indicadorConcursoEspecial: Int?,
    val listaDezenas: List<String>?,
    val listaDezenasSegundoSorteio: Any?,
    val listaMunicipioUFGanhadores: List<ListaMunicipioUFGanhadores>?,
    val listaRateioPremio: List<ResultFederalModel>,
    val listaResultadoEquipeEsportiva: Any?,
    val localSorteio: String? = "",
    val nomeMunicipioUFSorteio: String? = "",
    val nomeTimeCoracaoMesSorte: String? = "",
    val numero: Int?,
    val numeroConcursoAnterior: Int?,
    val numeroConcursoFinal_0_5: Int?,
    val numeroConcursoProximo: Int?,
    val numeroJogo: Int?,
    val observacao: String? = "",
    val premiacaoContingencia: Any?,
    val tipoJogo: String?,
    val tipoPublicacao: Int?,
    val ultimoConcurso: Boolean?,
    val valorAcumuladoConcursoEspecial: Double?,
    val valorAcumuladoConcurso_0_5: Double?,
    val valorAcumuladoProximoConcurso: Double?,
    val valorArrecadado: Double?,
    val valorEstimadoProximoConcurso: Double?,
    val valorSaldoReservaGarantidora: Double?,
    val valorTotalPremioFaixaUm: Double?
)