package br.com.minhasortemegasena.model

data class LotteryModel(
    val acumulado: Boolean? = null,
    val dataApuracao: String? = null,
    val dataProximoConcurso: String? = null,
    val dezenasSorteadasOrdemSorteio: List<String>? = null,
    val exibirDetalhamentoPorCidade: Boolean? = null,
    val id: Any? = null,
    val indicadorConcursoEspecial: Int? = null,
    val listaDezenas: List<String>? = null,
    val listaDezenasSegundoSorteio: Any? = null,
    val listaMunicipioUFGanhadores: List<ListaMunicipioUFGanhadores>? = null,
    val listaRateioPremio: List<ListaRateioPremio>? = null,
    val listaResultadoEquipeEsportiva: Any? = null,
    val localSorteio: String? = null,
    val nomeMunicipioUFSorteio: String? = null,
    val nomeTimeCoracaoMesSorte: String? = null,
    val numero: Int? = null,
    val numeroConcursoAnterior: Int? = null,
    val numeroConcursoFinal_0_5: Int? = null,
    val numeroConcursoProximo: Int? = null,
    val numeroJogo: Int? = null,
    val observacao: String? = null,
    val premiacaoContingencia: Any? = null,
    val tipoJogo: String? = null,
    val tipoPublicacao: Int? = null,
    val ultimoConcurso: Boolean? = null,
    val valorAcumuladoConcursoEspecial: Double? = null,
    val valorAcumuladoConcurso_0_5: Double? = null,
    val valorAcumuladoProximoConcurso: Double? = null,
    val valorArrecadado: Double? = null,
    val valorEstimadoProximoConcurso: Double? = null,
    val valorSaldoReservaGarantidora: Double? = null,
    val valorTotalPremioFaixaUm: Double? = null
)